name: emr

services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        networks:
            - emr-network

    app:
        image: fayaz321/emr:latest
        container_name: emr
        depends_on:
            - mongodb
        ports:
            - "${PORT}:5050"
        env_file:
            - .env
        networks:
            - emr-network

volumes:
    mongodb_data:

networks:
    emr-network:
        driver: bridge
